require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
rn_maps_path = '../node_modules/react-native-maps'

platform :ios, '10.0'

target 'zipanda' do
  

  #pod 'react-native-maps', path: rn_maps_path
  #pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  #pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'

  #pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS

  #pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'

  
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  #pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  #use_react_native!(:path => config["reactNativePath"])

  target 'zipandaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'zipanda-tvOS' do
  # Pods for zipanda-tvOS

  target 'zipanda-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-places'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
